<%--
    Document   : admin-pins
    Created on : Jun 10, 2020, 3:27:22 PM
    Author     : Jevison7x
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<jsp:useBean id="adminPin" class="com.valdbms.adminpins.AdminPin"/>
            <!-- MAIN CONTENT-->
            <div id="pin-numbers" class="main-content">
                <style type="text/css" scoped>
                    #generate-pin-btn {
                        margin-bottom: 10px;
                    }
                    h5 {
                        margin-bottom: 10px;
                    }
                </style>
                <div class="section__content section__content--p30">
                    <div class="row m-t-30">
                        <div class="col-md-12">
                            <c:if test="${param.success ne null}">
                                <h5>Pin was generated successfully!</h5>
                            </c:if>
                            <button id="generate-pin-btn" class="btn btn-primary"><i class="fa fa-gears"></i> Generate New Pin</button>
                            <!-- DATA TABLE-->
                            <div class="table-responsive m-b-40">
                                <table class="table table-borderless table-data3">
                                    <thead>
                                        <tr>
                                            <th>Pin</th>
                                            <th>Generated By</th>
                                            <th>Date Generated</th>
                                            <th>Used By</th>
                                            <th>Date Used</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    <c:forEach var="adminPin" items="${adminPins}">
                                        <tr>
                                            <td>${adminPin.pin}</td>
                                            <td>${adminPin.generatedBy}</td>
                                            <td>
                                                <fmt:formatDate var="dateGenerated" value="${adminPin.dateGenerated}" pattern="MMM dd, yyyy - hh:mm a"/>
                                                ${dateGenerated}
                                            </td>
                                            <td class="process">${adminPin.usedBy}</td>
                                            <td>
                                                <fmt:formatDate var="dateUsed" value="${adminPin.dateUsed}" pattern="MMM dd, yyyy - hh:mm a"/>
                                                ${dateUsed}
                                            </td>
                                        </tr>
                                    </c:forEach>
                                    </tbody>
                                </table>
                            </div>
                            <!-- END DATA TABLE-->
                        </div>
                        <jsp:include page="../WEB-INF/fragments/footer.jsp"/>
                    </div>
                </div>
            </div>
            <!-- END MAIN CONTENT-->
